export const testPath = {
  isTop: (pathname: string) => /^\/$/.test(pathname),
  isTokyoHome: (pathname: string) => /^\/tokyo\/?$/.test(pathname),
  isTokyoRoute: (pathname: string) => /^\/tokyo\/route\/?$/.test(pathname),
  isSaitamaHome: (pathname: string) => /^\/saitama\/?$/.test(pathname),
  isSaitamaRoute: (pathname: string) => /^\/saitama\/route\/?$/.test(pathname),
  isChibaHome: (pathname: string) => /^\/chiba\/?$/.test(pathname),
  isChibaRoute: (pathname: string) => /^\/chiba\/route\/?$/.test(pathname),
  isKanagawaHome: (pathname: string) => /^\/kanagawa\/?$/.test(pathname),
  isKanagawaRoute: (pathname: string) => /^\/kanagawa\/route\/?$/.test(pathname),
  isYamanashiHome: (pathname: string) => /^\/yamanashi\/?$/.test(pathname),
  isYamanashiRoute: (pathname: string) => /^\/yamanashi\/route\/?$/.test(pathname),
  isSpotPage: (pathname: string) => /^\/spot\/\d+\/?$/.test(pathname),
  isWebsiteMap: (pathname: string) => /^\/websitemap\/?$/.test(pathname),
  isWebsitePolicy: (pathname: string) => /^\/website-policy\/?$/.test(pathname),
  isTermsOfUse: (pathname: string) => /^\/terms-of-use\/?$/.test(pathname),
  isPrivacyPolicy: (pathname: string) => /^\/privacy-policy\/?$/.test(pathname),
}
