name: autoDeploy

on:
  push:
    branches:
      - staging

jobs:
  Deploy-Action:
    name: Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Build Project
        run: |
          npm ci
          npm run build

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          server-dir: www.test-preview.space/walking-together/ # デプロイするサーバーのディレクトリ
          local-dir: ./dist/ # デプロイするローカルのディレクトリ
